version = 0.1

[default.global.parameters]
stack_name = "poof-control-plane"
region = "ap-south-1"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = true
